name: build-ios-app
on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm ci
      - run: npx cap add ios
      - run: npx cap add android
      - run: fastlane icons
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
