name: build-android-app
on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Build Ionic App
        run: |
          npm ci
          npx cap add android
          ionic build --prod --aot --output-hashing=all && npx cap sync

      - name: Setup Ruby and Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.2'

      - name: Fastlane Android App
        env:
          ANDROID_KEYSTORE_FILE: ${{ secrets.ANDROID_KEYSTORE_FILE }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEYSTORE_ALIAS: ${{ secrets.ANDROID_KEYSTORE_ALIAS }}
          GOOGLE_PLAY_STORE_API_KEY_JSON: ${{ secrets.GOOGLE_PLAY_STORE_API_KEY_JSON }}
        run: |
          gem install bundler
          bundle install
          fastlane install_plugins
          fastlane android internal
