name: Validate Fastlane Match
on:
  workflow_dispatch:

jobs:
  validate-fastlane-match:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Check Fastlane Match
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          KEYCHAIN_PATH: ~/Library/Keychains/signing_temp.keychain-db
        run: |
          fastlane match
          
