name: Validate Fastlane Match
on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Check Fastlane Match
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          KEYCHAIN_PATH: ~/Library/Keychains/signing_temp.keychain-db
        run: |
          bundle exec fastlane match
          
