name: Validate Fastlane Match
on:
  workflow_dispatch:

jobs:
  validate-fastlane-match:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check Fastlane Match
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          KEYCHAIN_PATH: ~/Library/Keychains/signing_temp.keychain-db
        run: |
          bundle exec fastlane match
          
